package sitemapapp;

import org.apache.log4j.LogManager;
import org.apache.log4j.Logger;
import sitemapapp.service.PageService;
import sitemapapp.service.impl.PageServiceImpl;
import sitemapapp.utils.CheckSite;

import java.io.IOException;
import java.util.Scanner;

public class Main {
    static Logger rootLogger = LogManager.getRootLogger();

    public static void main(String[] args) throws IOException {

        rootLogger.info("The app has been started.");
        String startUrl;
        Scanner scanner = new Scanner(System.in);
        while (true){
            rootLogger.info("Enter the url of site: ");
            startUrl = CheckSite.correctingUrl(scanner.nextLine());
            if(CheckSite.checkResponseOfSite(startUrl)){
                break;
            }
            rootLogger.warn("The site not response, correct the url");
        }
        rootLogger.info("Enter the name of output file (if you don't want custom name, the name will be generated by site name): ");
        String fileName = scanner.nextLine();
        rootLogger.info("Set the sleep time of threads to bypass protection against DDoS attacks (value in milliseconds), default value (write 0) is 100 milliseconds: ");
        long threadSleepTime = 0;
        String enteredSleepTime = scanner.nextLine();
        if(!enteredSleepTime.equals("")) {
            try {
                threadSleepTime = Long.parseLong(enteredSleepTime);
            } catch (NumberFormatException e) {
                rootLogger.info("This is not long number. sleep time will set to default value.");
            }

        }
        else rootLogger.info("sleep time will set to default value.");
        scanner.close();
        rootLogger.info("Creating map started...");
        PageService pageService = new PageServiceImpl(startUrl, fileName, threadSleepTime);
        pageService.getSiteMap();
        rootLogger.info("The app has been ended");
    }
}
